---
- hosts: 127.0.0.1
  connection: local
  gather_facts: true
  tasks:
  - name:  Create symbolic link  for .bashrc
    local_action: file src="{{ ansible_env['HOME'] }}/.dotfiles/bashrc" dest="{{ ansible_env['HOME'] }}/.bashrc" state=link
  - name:  Create symbolic link gitconfig
    local_action: file src="{{ ansible_env['HOME'] }}/.dotfiles/gitconfig" dest="{{ ansible_env['HOME'] }}/.gitconfig" state=link
